### ISSUE TITLE
What does mean the subsample?

### ISSUE THREAD

**Issue by ryukyungjoon** [eigenvivek/DiffPose#34]
Can you tell me what the subsample value means? Is it related to fov?
What are the values of delx and dely?
I think it can be a key to solving the problem I'm facing now.

![image](https://github.com/user-attachments/assets/b1748532-f8ff-4d41-9f6b-035de6a8f721)

Thank you.

**Comment by eigenvivek** [comment]
`subsample` is merely the factor by which you downsample (if `subsample > 1`) an image.

For example, if the original X-ray is 100 x 100 pixels with 1 mm isotropic pixel spacing and you apply a factor of `subsample=2`, the new image will be 50 x 50 pixels with 2 mm isotropic pixel spacings.

Because pixel size and spacing are inversely scaled by `subsample`, the FOV actually remains constant.

**Comment by ryukyungjoon** [comment]
Thank you for answer. 
So, what do you mean by the constant values you used to calculate the subsample and delx variables?

subsample = (1536 - 100) / height
delx = 0.194 * subsample

what does mean the 1536? , 100? and 0.194?

Thank you.

**Comment by eigenvivek** [comment]
`1536` is the pixel dimension of the original image (it's square)

`100` is subtracted because a 50 pixel edge is cropped to remove the effect of the collimator

`height` is the desired dimension of the image we want to render (256 for all diffpose experiments)

`0.194` is the pixel size in the deepfluoro dataset

**Comment by ryukyungjoon** [comment]
Thank you for answer.

My dataset got 0.337890625 for pixel spacing from the dicom original volume, and set the desired detector size to 285, which is the same as the original DRR size. The pixel dimension was set to 512 which is the size of a single dicom file.

![image](https://github.com/user-attachments/assets/385b2f06-fa9a-44f1-b548-1c69f52e3203)
isocenter pose DRR image

![000](https://github.com/user-attachments/assets/8ccdbb01-d40a-440f-8051-e5aa32d59f1d)
True DRR image

By the way, the result is shown in the image below.
Additionally, I'm using APview's DRR, just to say if it will help me get an answer.

**Comment by eigenvivek** [comment]
HI @ryukyungjoon , it looks like your first DRR has anisotropic spacing. Are you setting `delx` and `dely` separately?

**Comment by ryukyungjoon** [comment]
Hi Vivek,
Thank you for answering
The problem I had was that the original volume was resampled and DRR was generated abnormally.
Thanks to your advice, thank you so much and I hope you have a great day :)

**Comment by eigenvivek** [comment]
great glad to hear your issue was solved!
